print("This is the divsion machine")
print("Type in youre first number:")
firstnumber = input()
print("Type in youre second number:")
secondnumber = input()
answer = float(firstnumber) / float(secondnumber)
print(answer)
print("Now, we will do additition")
print("Type in the first number:")
firstnumber2 = input()
print("Type in the second number")
secondnumber2 = input()
answer2 = float(firstnumber2) + float(secondnumber2)
print(answer2)
print("Now we will do subtraction")
print("Type in the first number")
firstnumber3 = input()
print("Type in the second number")
secondnumber3 = input()
answer3 = float(firstnumber3) - float(secondnumber3)
print(answer3)
print("now we will do multiplication tpye in the first number")
firstnumber4 = input()
print("now type in the second number")
secondnumber4 = input()
answer4 = float(firstnumber4) * float(secondnumber4)
print(answer4)
print("Now we will do modlous")
print("Type in the first number")
firstnumber6 = input()
print("Type in the second number")
secondnumber6 = input()
answer6 = float(firstnumber6) % float(secondnumber6)
print(answer6)
      
      

      